require:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  NewCops: disable
  Exclude:
    - db/migrate/*
    - db/schema.rb
